### ISSUE TITLE
Is the code can be used for the simulation of landslide tsunami?

### ISSUE THREAD

**Issue by xuhenry** [TUM-I5/SWE#5]
Hello,
Is the code can be used for the simulation of landslide tsunami?
Thanks a lot!
Best regard,
Henry

**Comment by baderml** [comment]
Dear Henry,
SWE is a simple code that we primarily use for teaching purposes (primarily HPC-oriented). It only covers the (single-layer) hydrostatic shallow water equations (with bathymetry). We haven't considered landslides, so far. 
I guess you could formulate a landslide as a time-dependent change in bathymetry data and pipe that into the simulation. Can't tell whether the results will be suitable for your intended purpose. 

If you require a validated code for landslide tsunamis, I'd recommend Landslide-HySEA: https://edanya.uma.es/hysea/index.php/models/landslide-hysea

Best regards

Michael
